dependencies:
  - name: redis
    version: 0.4.5
    repository: file://./subcharts/redis
  - name: ckan-solr
    version: 0.0.1
    repository: file://./subcharts/ckan-solr
  - name: postgresql
    version: 0.4.0
    repository: file://./subcharts/postgresql
  - name: ckan-core
    version: 0.0.1
    repository: file://./subcharts/ckan-core
