apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-init
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  postgresqlInitdbd: |
    {{ template "postgresqlInitdbd" . }}
