kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "fullname" . }}-database-accessor
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "fullname" . }}-database-access
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}-database-user
  namespace: {{ .Release.Namespace }}
